name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  # Every Saturday at 12:00pm UTC
  schedule:
    - cron: '0 12 * * 6'

jobs:
  ci:
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
