name: Keepalive

on:
  workflow_dispatch:
  # The 4th of every month at 10:50am UTC
  schedule:
    - cron: '50 10 4 * *'

jobs:
  keepalive:
    name: Keepalive
    runs-on: ubuntu-latest
    steps:
      - name: Keepalive
        uses: silverstripe/gha-keepalive@v1
